Fix certain invalid inputs causing segfault on expectation ops.
tensorflow/quantum pull request #388
Opened 2020-09-17 08:02 UTC by MichaelBroughton

2020-09-17 21:55 UTC, zaqqwerty requested changes
In the original issue, the last line in the OP's example code is:
`print(expectation([c1, c2], symbol_names=[a, b], symbol_values=[[0.,0.]], operators=[m1, m2])) # segmentation fault`
Can this scenario be tested in the expectation and sampled expectation layer test files?

2020-09-17 22:27 UTC, peezoslug approved these changes

2020-09-17 23:00 UTC, MichaelBroughton commented
Good idea @zaqqwerty , added tests for all layers. Our keras layer tests are kind of messy, maybe we should open an issue to clean things up a bit.

2020-09-18 01:33 UTC, zaqqwerty approved these changes
LGTM

2020-09-18 01:46 UTC, merged