Added missing docstring for inner product.
tensorflow/quantum pull request #392
Opened 2020-09-19 01:31 UTC by MichaelBroughton

Accidentally merged without adding. Here is the docstring snippets.

2020-09-20 16:19 UTC, zaqqwerty requested changes
spelling nits

2020-09-20 16:19 UTC, zaqqwerty commented on tensorflow_quantum/core/ops/math_ops/inner_product_op.py
> +    Compute (potentailly many) inner products betwen the given circuits and
spelling, `potentailly` ==> `potentially`

2020-09-20 16:19 UTC, zaqqwerty commented on tensorflow_quantum/core/ops/math_ops/inner_product_op.py
>          (\text{symvol_values[i]}) | \psi_{\text{other_programs[j]}} \rangle
spelling, `symvol_values` ==> `symbol_values`

2020-09-21 20:05 UTC, MichaelBroughton commented on tensorflow_quantum/core/ops/math_ops/inner_product_op.py
> +    Compute (potentailly many) inner products betwen the given circuits and
Fixed.

2020-09-21 20:05 UTC, MichaelBroughton commented on tensorflow_quantum/core/ops/math_ops/inner_product_op.py
>          (\text{symvol_values[i]}) | \psi_{\text{other_programs[j]}} \rangle
Fixed.

2020-09-21 21:39 UTC, zaqqwerty approved these changes
LGTM

2020-09-22 00:17 UTC, merged