Research update 2p3p0
tensorflow/quantum pull request #395
Opened 2020-09-21 13:42 UTC by zaqqwerty

Updated tf to 2.3.0 in research branch.  Will wait for #343 to go in so that I can run the notebooks with this update before merging.

2020-10-01 01:42 UTC, MichaelBroughton commented
Can we upgrade to 2.3.1 here ?

2020-10-07 15:55 UTC, MichaelBroughton requested changes
Can we change this to 2.3.1 and remove some of the names that have "Copy_***" in them ? After that I think we'll be good to merge this into research.

2020-10-07 15:55 UTC, MichaelBroughton commented on binary_classifier/binary_classifier.ipynb
> +      "name": "Copy of TFQ_Example_BinaryClassifier.ipynb",
Don't think we want to change the name here.

2020-10-07 15:55 UTC, MichaelBroughton commented on control/control.ipynb
> +      "name": "Copy of TFQ_Example_DNN_LSTM_Qcontrol_application.ipynb",
Copy

2020-10-08 05:16 UTC, zaqqwerty commented
Denoised this PR in #408

2020-10-08 05:16 UTC, closed without merging