Fix warnings of c++ compilation
tensorflow/quantum pull request #476
Opened 2021-02-07 06:38 UTC by jaeyoo

https://github.com/tensorflow/quantum/issues/475

2021-02-08 08:49 UTC, jaeyoo commented
Please merge this one earlier than https://github.com/tensorflow/quantum/pull/477  if possible

2021-08-26 18:23 UTC, zaqqwerty requested changes
Thanks for the updates, have a couple questions.  If the resolution of the static function stuff is unclear we can merge the rest without touching `util_qsim`, this will just leave unused function warnings, which is a big improvement :)

2021-09-30 05:46 UTC, jaeyoo commented on tensorflow_quantum/core/ops/math_ops/tfq_inner_product.cc
> +    for (std::vector<std::vector<qsim::GateFused<QsimGate>>>::size_type i = 0;
DONE

2021-09-30 05:47 UTC, jaeyoo commented on tensorflow_quantum/core/ops/math_ops/tfq_inner_product.cc
> +      for (std::vector<std::vector<qsim::GateFused<QsimGate>>>::size_type j = 0;
Done

2021-09-30 05:47 UTC, jaeyoo commented on tensorflow_quantum/core/ops/math_ops/tfq_inner_product.cc
> +      for (std::vector<qsim::GateFused<QsimGate>>::size_type j = 0;
Done

2021-09-30 05:47 UTC, jaeyoo commented on tensorflow_quantum/core/ops/math_ops/tfq_inner_product.cc
> +        for (std::vector<qsim::GateFused<QsimGate>>::size_type k = 0;
Done

2021-09-30 05:47 UTC, jaeyoo commented on tensorflow_quantum/core/ops/math_ops/tfq_inner_product.cc
> +          for (std::vector<qsim::GateFused<QsimGate>>::size_type j = 0;
Done

2021-09-30 05:47 UTC, jaeyoo commented on tensorflow_quantum/core/ops/math_ops/tfq_inner_product.cc
> +        for (std::vector<qsim::GateFused<QsimGate>>::size_type k = 0;
Done

2021-09-30 05:48 UTC, jaeyoo commented on scripts/test_all.sh
> +test_outputs=$(bazel test -c opt --experimental_repo_remote_exec --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt="-msse2" --cxxopt="-msse3" --cxxopt="-msse4" --cxxopt="-Wno-unused-function" --notest_k
`--cxxopt="-Wno-unused-function"` is reverted, and let me defer fixing `BalanceTrajectory` later. Done.

2026-05-13 04:23 UTC, mhucka commented
Many of these have been fixed since the time this PR was written. Some remaining warnings are addressed by https://github.com/tensorflow/quantum/pull/1070. 

I believe now what remains unresolved is warnings due to code in external libraries. So, I think it's reasonable to close this PR when https://github.com/tensorflow/quantum/pull/1070 is merged.

2026-05-22 22:07 UTC, closed without merging