Quantum embedding
tensorflow/quantum pull request #606
Opened 2021-07-10 06:09 UTC by tonybruguier

This PR tries to re-create a series of paper by Schuld et al. regarding the universality of quantum embeddings

2021-07-10 06:19 UTC, tonybruguier commented
I ran some rudimentary profiling. More than happy to receive feedback on this (in addition to code quality, of course):

![profile_pie_chart](https://user-images.githubusercontent.com/14946972/125153953-18fca600-e10c-11eb-9e4d-526cf4ed35e0.png)

![profile_host_side](https://user-images.githubusercontent.com/14946972/125153942-0b472080-e10c-11eb-856d-3ded52c284cd.png)

![profile_tf_ops](https://user-images.githubusercontent.com/14946972/125153957-22860e00-e10c-11eb-927a-d52e45c632a9.png)

2021-07-15 23:36 UTC, MichaelBroughton requested changes
This is a good start. Normally in our research branch, we like to see a simple application demonstration in the code. In the case of this embedding, would you mind setting up a simple training loop with a model and some data in order to show off how things work with the Layer ?

2021-07-17 04:24 UTC, tonybruguier commented
The unit tests already had a training loop, but it's a good point nonetheless, so I added a Jupyter notebook. PTAL.

2021-07-21 00:19 UTC, MichaelBroughton approved these changes

2021-07-21 00:19 UTC, merged