Add `tfq.math.1d_expectation` for 1D MPS
tensorflow/quantum pull request #610
Opened 2021-08-03 22:30 UTC by jaeyoo

Resolve #603 1st of the three ops.

2021-08-04 20:11 UTC, MichaelBroughton requested changes
This is a great first pass @jaeyoo ! Would you be able to add some tests that verify expectations values computed using cirq's built in expectation calculation functions ? Also removing some of the print statements from the code  :)

2021-08-06 06:34 UTC, jaeyoo commented on tensorflow_quantum/core/src/program_resolution.cc
> +                        "An operation contains more than two qubits.");
done. thank you for the catch :)

2021-09-06 19:05 UTC, MichaelBroughton commented
@jaeyoo any updates on this ? (My workstation has gone offline and won't be into the office for a while to turn it back on).

2021-09-06 19:15 UTC, jaeyoo commented
> @jaeyoo any updates on this ? (My workstation has gone offline and won't be into the office for a while to turn it back on).

I am still working on how to fix the `delete` issue...

2021-09-30 08:14 UTC, jaeyoo commented
@MichaelBroughton I could fix the error finally. It was not easy because it had multiple reasons.

1. It turns out that we can't use `tfq::QsimFor` : I realized that the current `MPSSimulator` doesn't accept `qsim::SequantialFor`. It accepts `qsim::For` only. On top of it, for initialization, dummy value 1 is used for `ForArgs`, not `tfq_for` value.
2. Even if the theoretical minimum of qsim MPS bond_dim is 2 (as shown [here](https://github.com/quantumlib/qsim/blob/5a7a1319abe95d76115d5ba428d2e9bd3f097d30/lib/mps_statespace.h#L98)), but the real test seems to require minimum 4 (as qsim MPSSimulator test code.), because the weird `double free` error occurred from it. After increasing the `bond_dim` from `2` to `4`, the error's gone. So I want to make sure if there is a good test scenario to deal with which circuit accepts `bond_dim=2` or not. could you please recommend it?
3. we can't use `ApplyFusedGate()` anymore. On top of it, `ApplyGate()` should be done with `main_circuits` not with `fused_circuits`.
4. Likewise, we can't use `ComputeExpectation`. We need to add similar function using `ApplyGate()`, not `ApplyFusedGate()`

Thank you so so much for your kind patience.

2021-09-30 08:33 UTC, jaeyoo commented
Failed at (//tensorflow_quantum/core/ops/noise:noisy_samples_op_test )[https://github.com/tensorflow/quantum/pull/610/checks?check_run_id=3753494646#step:6:897] May i just re-run the test?

2021-09-30 22:59 UTC, jaeyoo commented
PTAL

Note: `qsim::ApplyFusedGate` will be supported after `qsim==0.10.3` due to https://github.com/quantumlib/qsim/issues/395.

2021-10-01 18:24 UTC, MichaelBroughton commented
We just cut a release here: https://github.com/quantumlib/qsim/releases/tag/v0.10.3-dev%2B20211001

Could we try upgrading to this new qsim version ?

2021-10-01 19:01 UTC, jaeyoo commented
> We just cut a release here: https://github.com/quantumlib/qsim/releases/tag/v0.10.3-dev%2B20211001
> 
> Could we try upgrading to this new qsim version ?

Sure, it's my pleasure. Done.

2021-10-04 16:57 UTC, MichaelBroughton requested changes
Looking great! Just a few moderate sized changes then we should be good to merge!

2021-10-04 16:57 UTC, MichaelBroughton commented on tensorflow_quantum/core/ops/math_ops/simulate_mps_test.py
> +    def test_simulate_mps_1d_expectation_results(self):
This is a good start. Could we add a few more tests here that do the following:

1. Test with all single qubit gates in `tfq.get_supported_gates`
2. Test with all single qubit gates in `tfq.get_supported_gates.controlled_by(a_qubit)` and ensure that this fails or passes accordingly)
3. Test that all two qubit gates in `tfq.get_supported_gates` works.
4. Ensure that the empty case works as expected

2022-01-04 09:26 UTC, MichaelBroughton commented
I went ahead and cleaned up the implementation a little bit. Notable changes:

1. Removed the use of `ApplyFusedGate`. On closer inspection if two qubits that weren't adjacent to one another got fused together, things would break.
2. Added in the `swap_endian` option for parsing. The mps simulator in qsim has different endianness from the state vector simulator. Working in a proper fix to qsim would take a very long time so this is a workaround until we can get this fixed. https://github.com/quantumlib/qsim/issues/492
3. Removed the `ComputeLarge` since MPS has a much smaller memory footprint
4. Added a few more tests.

2022-01-04 19:01 UTC, jaeyoo reviewed
LGTM for me, but I can't approve my PR. :) @MichaelBroughton

2022-01-04 19:35 UTC, merged